apiVersion: v1
kind: Service
metadata:
  name: postgres-operator
  namespace: x-runtime
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: postgres-operator
