use_frameworks!

platform :ios, ‘11.0’
target 'BorrowBackMachine' do
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'HyphenateChat'
pod 'EaseIMKit'
pod 'HyphenateChat', '3.8.1'
pod 'AgoraRtcEngine_iOS'
pod 'EaseCallKit'
pod 'FMDB'

end

