name: dan_box
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  effective_dart: 1.3.1
  get: 4.1.4
  styled_widget: 0.3.1
  flutter_screenutil: 5.0.0+2
  line_icons: 2.0.1
  agora_rtc_engine: 4.0.1
  permission_handler: 8.0.0+2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true

