version: "3.6"

services:
  database:
    image: mysql:5.7
    restart: always
    container_name: goaskme-db
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ./data/db-data:/var/lib/mysql

  nginx:
    image: nginx-custom
    build: ./nginx
    container_name: goaskme-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/logs:/var/log/nginx
      - ./data/ssl/.well-known:/.well-known
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./www/goaskme-api:/www/goaskme-api
      - ./www/goaskme-mall:/www/goaskme-mall
      - ./www/m-goaskme-mall:/www/m-goaskme-mall
      - pma-root:/www/pma # phpMyAdmin
    links:
      - php:php
    extra_hosts:
      - "localhost:127.0.0.1"
    labels:
      - sh.acme.autoload.domain=niclalalla.top
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off http://localhost/get-health || exit 1"]
      interval: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

#  acme.sh:
#    image: neilpang/acme.sh
#    container_name: acme.sh
#    command: daemon
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./data/ssl/acmeout:/acme.sh
#      - ./data/ssl/.well-known:/.well-known
#    environment:
#      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=niclalalla.top
#      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/ssl/certs/niclalalla.top/key.pem
#      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/ssl/certs/niclalalla.top/cert.pem"
#      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/ssl/certs/niclalalla.top/ca.pem"
#      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/ssl/certs/niclalalla.top/full.pem"
#      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="kill 1"

  php:
    image: php-fpm-flarum:latest
    build: ./php-fpm 
    container_name: goaskme-php-fpm
    restart: always
    expose:
      - 9000
    volumes:
      - ./data/logs:/var/log
      - ./www/goaskme-api:/www/goaskme-api
      - ./www/goaskme-mall:/www/goaskme-mall
      - ./www/m-goaskme-mall:/www/m-goaskme-mall
      # - ./xunsearch/app.ini:/wwwroot/vendor/jjandxa/flarum-ext-chinese-search/app.ini
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm"]
      interval: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  pma:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    container_name: goaskme-pma
    restart: always
    environment: 
      - PMA_HOST=goaskme-db
    volumes:
      - pma-root:/var/www/html

  # xunsearch:
  #   image: xunsearch:1.4.13
  #   container_name: site-xunsearch
  #   build: ./xunsearch
  #   restart: always
  #   expose:
  #     - 8383
  #     - 8384

volumes: 
  pma-root:
