/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing */

#ifndef _Included_org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
#define _Included_org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    setCallback
 * Signature: (Lorg/lql/movie_together/ui/face/rawaudio/MediaPreProcessing/ProgressCallback;)V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_setCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    setVideoCaptureByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_setVideoCaptureByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    setAudioRecordByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_setAudioRecordByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    setAudioPlayByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_setAudioPlayByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    setBeforeAudioMixByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_setBeforeAudioMixByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    setAudioMixByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_setAudioMixByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    setVideoDecodeByteBuffer
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_setVideoDecodeByteBuffer
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_lql_movie_together_ui_face_rawaudio_MediaPreProcessing
 * Method:    releasePoint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lql_movie_1together_ui_face_rawaudio_MediaPreProcessing_releasePoint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
